<?php

/**
 * @file
 * Contains engineering_profile_helper.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function engineering_profile_helper_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the engineering_profile_helper module.
    case 'help.page.engineering_profile_helper':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Engineering Profile Helper module') . '</p>';
      $output .= '<p>' . t('This module holds helper code specifically for the engineering_profile.').'</p>';
      return $output;

    default:
  }
}

/**
 * @param $form
 * @param $form_state
 *
 */
function engineering_profile_form_views_exposed_form_alter(&$form, &$form_state){
  // Changes the label of the first item on dropdown for exposed filter on /spotlight
  if($form["#id"] == 'views-exposed-form-spotlights-block-1'){
    $form['tid']['#options']["All"] = t('All Departments');
    $form['tid_1']['#options']["All"] = t('All People');
  }
}
