<?php

/**
 * @file
 * Contains engineering_profile_helper.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function engineering_profile_helper_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the engineering_profile_helper module.
    case 'help.page.engineering_profile_helper':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Engineering Profile Helper module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function engineering_profile_helper_theme() {
  return [
    'engineering_profile_helper' => [
      'render element' => 'children',
    ],
  ];
}
