<?php

/**
 * @file
 * Contains engineering_profile_helper.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\views\ViewExecutable;
use \Drupal\Core\Render\Element;

/**
 * Implements hook_help().
 */
function engineering_profile_helper_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the engineering_profile_helper module.
    case 'help.page.engineering_profile_helper':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Engineering Profile Helper module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function engineering_profile_helper_theme() {
  return [

  ];
}

/**
 * @param $form
 * @param $form_state
 *
 */
function engineering_profile_form_views_exposed_form_alter(&$form, &$form_state){
  // Changes the label of the first item on dropdown for exposed filter on /spotlight
  if($form["#id"] == 'views-exposed-form-spotlights-block-1'){
    $form['tid']['#options']["All"] = t('All Departments');
    $form['tid_1']['#options']["All"] = t('All People');
  }
}

/**
 * implements hook_views_pre_render
 */
function engineering_profile_helper_views_data_alter(array &$data) {

  //dpm($data);
}

/*
function engineering_profile_helper_entity_display_build_alter(&$build, $context){
  $replacement_alt_tag = null;
  foreach (Element::children($build) as $field_name) {
    $element =& $build[$field_name];

    //dpm($field_name);
    if ($field_name == "su_news_banner_media_caption"){
      $replacement_alt_tag = $element[0]['#context']['value'];
      //dpm($element);
    }
    //if ($field_name == "su_news_banner_media_caption")

    if (!empty($element['#field_type'])
    && $element['#field_type'] == 'entity_reference'
    && $element['#formatter'] == 'media_responsive_image_formatter') {
      foreach($element['#items'] as $key => $item){
        if (empty($element['#options']['attributes']['alt'])){
          $element['#options']['attributes']['alt'] = "presentation image";
          //$image = $item->entity;
          dpm($item);
        }
        //$image = $item->entity;
        //dpm($item);
      }

    }
  }
}
*/
