<?php

/**
 * @file
 * Contains engineering_magazine.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function engineering_magazine_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the engineering_magazine module.
    case 'help.page.engineering_magazine':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Modifies stanford_news to work for the School of Engineering Magazine content.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function engineering_magazine_theme($existing, $type, $theme, $path) {
  return [
    'magazine_navigation_block' => [
      'template' => 'block/magazine-navigation',
      'variables' => [
        'topics' => null,
      ],
    ],
    'magazine_curtain_block' => [
      'template' => 'block/magazine-curtain-block',
      'variables'=> [
        'curtain_content' => null,
      ],
    ],
  ];
}

