adding:
  dependencies:
    module:
      - graphql
  permissions:
    - 'access patterns page'
    - 'execute graphql_compose_server arbitrary graphql requests'
    - 'execute graphql_compose_server persisted graphql requests'
    - 'view own su_site_algolia'
    - 'view own su_site_algolia_id'
    - 'view own su_site_algolia_index'
    - 'view own su_site_algolia_search'
    - 'view su_site_algolia'
    - 'view su_site_algolia_id'
    - 'view su_site_algolia_index'
    - 'view su_site_algolia_search'
removing: {  }
