adding:
  module:
    dblog: 0
    devel: 0
    devel_php: 0
    engineering_magazine: 0
    engineering_profile_helper: 0
    views_autosubmit: 0
  theme:
    engineering: 0
removing:
  module:
    graphql_compose_blocks: 0
    graphql_compose_edges: 0
    graphql_compose_image_style: 0
    graphql_compose_metatags: 0
