adding:
  dependencies:
    module:
      - jumpstart_ui
  third_party_settings:
    layout_builder:
      sections:
        -
          layout_id: defaults
          layout_settings:
            label: Header
            extra_classes: 'magazine-header magazine-topics__term-name magazine-news__heading'
            centered: centered-container
            columns: default
          components:
            1a33ec3b-a4db-4c29-9606-981a1a26b38e:
              uuid: 1a33ec3b-a4db-4c29-9606-981a1a26b38e
              region: main
              configuration:
                id: 'field_block:taxonomy_term:magazine_topics:name'
                label: 'Taxonomy Name'
                label_display: '0'
                provider: layout_builder
                context_mapping:
                  entity: layout_builder.entity
                  view_mode: view_mode
                formatter:
                  type: entity_title_heading
                  label: hidden
                  settings:
                    tag: h1
                  third_party_settings:
                    empty_fields:
                      handler: ''
                    field_formatter_class:
                      class: magazine-topics__term-name
                    field_label:
                      label_value: ''
                      label_tag: ''
              weight: 0
              additional: {  }
        -
          layout_settings:
            label: 'Topic Stories'
            context_mapping: {  }
          components:
            83a74267-7bcd-4b9f-b31f-8da1a7a8a40e:
              uuid: 83a74267-7bcd-4b9f-b31f-8da1a7a8a40e
              region: content
              configuration:
                id: 'views_block:magazine-block_3'
                label: ''
                label_display: '0'
                provider: views
                context_mapping: {  }
                views_label: ''
                items_per_page: 0
              weight: 0
              additional: {  }
        -
          components:
            83a74267-7bcd-4b9f-b31f-8da1a7a8a40e:
              configuration:
                items_per_page: 0
removing:
  dependencies:
    theme:
      - soe_basic
  third_party_settings:
    layout_builder:
      sections:
        -
          layout_id: soe_basic_full_width_header
          layout_settings:
            label: 'Magazine Navigation'
        -
          layout_settings:
            label: ''
        -
          components:
            83a74267-7bcd-4b9f-b31f-8da1a7a8a40e:
              configuration:
                items_per_page: none
