adding:
  features:
    favicon: 1
  logo:
    use_default: 1
  favicon:
    use_default: 1
  show_su_med_logo: 0
  lockup:
    option: l
    line1: Engineering
  browser_sync:
    enabled: 0
    host: ''
    port: ''
removing:
  favicon:
    use_default: true
  features:
    favicon: true
  logo:
    path: ''
    use_default: true
  browser_sync:
    enabled: false
    host: localhost
    port: 3000
  clear_registry: false
  lockup:
    option: a
    line1: ''
  nav_dropdown_enabled: 0
