adding:
  dependencies:
    config:
      - core.entity_view_display.node.stanford_news.default
      - core.entity_view_display.node.stanford_page.default
  permissions:
    - 'configure editable stanford_news node layout overrides'
    - 'configure editable stanford_page node layout overrides'
removing: {  }
