adding:
  display:
    viewfield_block_1_graphql:
      display_options:
        defaults:
          arguments: true
removing:
  display:
    basic_page_type_list_graphql:
      display_options:
        arguments:
          term_node_taxonomy_name_depth:
            id: term_node_taxonomy_name_depth
            table: node_field_data
            field: term_node_taxonomy_name_depth
            relationship: none
            group_type: group
            admin_label: ''
            entity_type: node
            plugin_id: taxonomy_index_name_depth
            default_action: empty
            exception:
              value: all
              title_enable: false
              title: All
            title_enable: false
            title: ''
            default_argument_type: fixed
            default_argument_options:
              argument: ''
            summary_options:
              base_path: ''
              count: true
              override: false
              items_per_page: 25
            summary:
              sort_order: asc
              number_of_records: 0
              format: default_summary
            specify_validation: false
            validate:
              type: none
              fail: 'not found'
            validate_options: {  }
            break_phrase: true
            depth: '1'
            use_taxonomy_term_path: false
            vocabularies:
              basic_page_types: basic_page_types
        defaults:
          arguments: false
    viewfield_block_1_graphql:
      display_options:
        arguments:
          term_node_taxonomy_name_depth:
            id: term_node_taxonomy_name_depth
            table: node_field_data
            field: term_node_taxonomy_name_depth
            relationship: none
            group_type: group
            admin_label: ''
            entity_type: node
            plugin_id: taxonomy_index_name_depth
            default_action: empty
            exception:
              value: all
              title_enable: false
              title: All
            title_enable: false
            title: ''
            default_argument_type: fixed
            default_argument_options:
              argument: ''
            summary_options:
              base_path: ''
              count: true
              override: false
              items_per_page: 25
            summary:
              sort_order: asc
              number_of_records: 0
              format: default_summary
            specify_validation: false
            validate:
              type: none
              fail: 'not found'
            validate_options: {  }
            break_phrase: true
            depth: '1'
            use_taxonomy_term_path: false
            vocabularies:
              basic_page_types: basic_page_types
        defaults:
          arguments: false
