adding:
  dependencies:
    module:
      - engineering_magazine
  third_party_settings:
    layout_builder:
      sections:
        -
          components:
            bccee9cd-7740-4050-9652-ef35d2a40aaa:
              uuid: bccee9cd-7740-4050-9652-ef35d2a40aaa
              region: main
              configuration:
                id: magazine_navigation_block
                label: 'Magazine Navigation'
                label_display: '0'
                provider: engineering_magazine
                context_mapping: {  }
              weight: 0
              additional: {  }
removing: {  }
