adding:
  display:
    cards_graphql:
      id: cards_graphql
      display_title: 'GraphQL: Card Grid'
      display_plugin: graphql
      position: 99
      display_options:
        fields:
          title:
            id: title
            table: node_field_data
            field: title
            relationship: none
            group_type: group
            admin_label: ''
            entity_type: node
            entity_field: title
            plugin_id: field
            label: ''
            exclude: false
            alter:
              alter_text: false
              text: ''
              make_link: false
              path: ''
              absolute: false
              external: false
              replace_spaces: false
              path_case: none
              trim_whitespace: false
              alt: ''
              rel: ''
              link_class: ''
              prefix: ''
              suffix: ''
              target: ''
              nl2br: false
              max_length: 0
              word_boundary: true
              ellipsis: true
              more_link: false
              more_link_text: ''
              more_link_path: ''
              strip_tags: false
              trim: false
              preserve_tags: ''
              html: false
            element_type: ''
            element_class: ''
            element_label_type: ''
            element_label_class: ''
            element_label_colon: false
            element_wrapper_type: ''
            element_wrapper_class: ''
            element_default_classes: true
            empty: ''
            hide_empty: false
            empty_zero: false
            hide_alter_empty: true
            click_sort_column: value
            type: string
            settings:
              link_to_entity: true
            group_column: value
            group_columns: {  }
            group_rows: true
            delta_limit: 0
            delta_offset: 0
            delta_reversed: false
            delta_first_last: false
            multi_type: separator
            separator: ', '
            field_api_classes: false
        pager:
          type: full
          options:
            offset: 0
            pagination_heading_level: h4
            items_per_page: 3
            total_pages: null
            id: 0
            tags:
              next: 'Next ›'
              previous: '‹ Previous'
              first: '« First'
              last: 'Last »'
            expose:
              items_per_page: true
              items_per_page_label: items
              items_per_page_options: '3,6,9,12,15,18,21,24,27,30,33,36,39,42,45,48,51,54,57,60,63,66,69,72,75,78,81,84,87,90,93,96,99'
              items_per_page_options_all: true
              items_per_page_options_all_label: all
              offset: true
              offset_label: offset
            quantity: 9
        arguments:
          term_node_taxonomy_name_depth:
            id: term_node_taxonomy_name_depth
            table: node_field_data
            field: term_node_taxonomy_name_depth
            relationship: none
            group_type: group
            admin_label: 'Taxonomy Name: Audience or Type'
            entity_type: node
            plugin_id: taxonomy_index_name_depth
            default_action: ignore
            exception:
              value: all
              title_enable: false
              title: All
            title_enable: false
            title: ''
            default_argument_type: fixed
            default_argument_options:
              argument: ''
            summary_options:
              base_path: ''
              count: true
              override: false
              items_per_page: 25
            summary:
              sort_order: asc
              number_of_records: 0
              format: default_summary
            specify_validation: false
            validate:
              type: none
              fail: 'not found'
            validate_options: {  }
            break_phrase: true
            depth: '1'
            use_taxonomy_term_path: false
            vocabularies:
              event_audience: event_audience
              stanford_event_types: stanford_event_types
          term_node_taxonomy_name_depth_1:
            id: term_node_taxonomy_name_depth_1
            table: node_field_data
            field: term_node_taxonomy_name_depth
            relationship: none
            group_type: group
            admin_label: 'Taxonomy Name: Groups'
            entity_type: node
            plugin_id: taxonomy_index_name_depth
            default_action: ignore
            exception:
              value: all
              title_enable: false
              title: All
            title_enable: false
            title: ''
            default_argument_type: fixed
            default_argument_options:
              argument: ''
            summary_options:
              base_path: ''
              count: true
              override: false
              items_per_page: 25
            summary:
              sort_order: asc
              number_of_records: 0
              format: default_summary
            specify_validation: false
            validate:
              type: none
              fail: 'not found'
            validate_options: {  }
            break_phrase: true
            depth: '10'
            use_taxonomy_term_path: false
            vocabularies:
              stanford_event_groups: stanford_event_groups
          term_node_taxonomy_name_depth_2:
            id: term_node_taxonomy_name_depth_2
            table: node_field_data
            field: term_node_taxonomy_name_depth
            relationship: none
            group_type: group
            admin_label: 'Taxonomy Name: Subject'
            entity_type: node
            plugin_id: taxonomy_index_name_depth
            default_action: ignore
            exception:
              value: all
              title_enable: false
              title: All
            title_enable: false
            title: ''
            default_argument_type: fixed
            default_argument_options:
              argument: ''
            summary_options:
              base_path: ''
              count: true
              override: false
              items_per_page: 25
            summary:
              sort_order: asc
              number_of_records: 0
              format: default_summary
            specify_validation: false
            validate:
              type: none
              fail: 'not found'
            validate_options: {  }
            break_phrase: true
            depth: '10'
            use_taxonomy_term_path: false
            vocabularies:
              stanford_event_subject: stanford_event_subject
          term_node_taxonomy_name_depth_3:
            id: term_node_taxonomy_name_depth_3
            table: node_field_data
            field: term_node_taxonomy_name_depth
            relationship: none
            group_type: group
            admin_label: 'Taxonomy Name: Keywords & Tags'
            entity_type: node
            plugin_id: taxonomy_index_name_depth
            default_action: ignore
            exception:
              value: all
              title_enable: false
              title: All
            title_enable: false
            title: ''
            default_argument_type: fixed
            default_argument_options:
              argument: ''
            summary_options:
              base_path: ''
              count: true
              override: false
              items_per_page: 25
            summary:
              sort_order: asc
              number_of_records: 0
              format: default_summary
            specify_validation: false
            validate:
              type: none
              fail: 'not found'
            validate_options: {  }
            break_phrase: true
            depth: '10'
            use_taxonomy_term_path: false
            vocabularies:
              stanford_event_keywords: stanford_event_keywords
        style:
          type: graphql
          options:
            uses_fields: false
        row:
          type: graphql_entity
          options: null
        defaults:
          css_class: false
          pager: false
          style: false
          row: false
          fields: false
          arguments: false
        display_description: 'Grid - All Items'
        display_extenders: {  }
        graphql_query_name: stanfordEventsCardGrid
      cache_metadata:
        max-age: -1
        contexts:
          - 'languages:language_content'
          - 'languages:language_interface'
          - url
          - url.query_args
          - 'user.node_grants:view'
          - user.permissions
        tags: {  }
    list_page_graphql:
      display_title: 'GraphQL: - Default List -'
    past_events_list_block_graphql:
      display_options:
        pager:
          type: some
          options:
            items_per_page: 20
        sorts:
          su_event_date_time_value:
            expose:
              label: ''
              field_identifier: su_event_date_time_value
            exposed: false
          created:
            expose:
              label: ''
            exposed: false
removing:
  display:
    list_page_graphql:
      display_title: 'GraphQL: List'
      display_options:
        exposed_form:
          type: graphql
          options:
            submit_button: Apply
            reset_button: 0
            reset_button_label: Reset
            exposed_sorts_label: 'Sort by'
            expose_sort_order: 1
            sort_asc_label: Asc
            sort_desc_label: Desc
        sorts:
          su_event_date_time_value:
            id: su_event_date_time_value
            table: node__su_event_date_time
            field: su_event_date_time_value
            relationship: none
            group_type: group
            admin_label: ''
            plugin_id: date
            order: ASC
            expose:
              label: 'Date & Time - Start'
              field_identifier: startTime
            exposed: true
            granularity: second
          created:
            id: created
            table: node_field_data
            field: created
            relationship: none
            group_type: group
            admin_label: ''
            entity_type: node
            entity_field: created
            plugin_id: date
            order: DESC
            expose:
              label: 'Authored on'
              field_identifier: created
            exposed: true
            granularity: second
          title:
            id: title
            table: node_field_data
            field: title
            relationship: none
            group_type: group
            admin_label: ''
            entity_type: node
            entity_field: title
            plugin_id: standard
            order: ASC
            expose:
              label: Title
              field_identifier: title
            exposed: true
          changed:
            id: changed
            table: node_field_data
            field: changed
            relationship: none
            group_type: group
            admin_label: ''
            entity_type: node
            entity_field: changed
            plugin_id: date
            order: ASC
            expose:
              label: Changed
              field_identifier: changed
            exposed: true
            granularity: second
        defaults:
          sorts: false
      cache_metadata:
        contexts:
          - 'url.query_args:sort_by'
          - 'url.query_args:sort_order'
    past_events_list_block_graphql:
      display_options:
        pager:
          type: full
          options:
            pagination_heading_level: h4
            items_per_page: 21
            total_pages: null
            id: 0
            tags:
              next: 'Next ›'
              previous: '‹ Previous'
              first: '« First'
              last: 'Last »'
            expose:
              items_per_page: true
              items_per_page_label: items
              items_per_page_options: '3,6,9,12,15,18,21,24,27,30,33,36,39,42,45,48,51,54,57,60,63,66,69,72,75,78,81,84,87,90,93,96,99'
              items_per_page_options_all: true
              items_per_page_options_all_label: all
              offset: true
              offset_label: offset
            quantity: 9
        sorts:
          su_event_date_time_value:
            expose:
              label: 'Date & Time - Start'
              field_identifier: startTime
            exposed: true
          created:
            expose:
              label: 'Authored on'
            exposed: true
          changed:
            id: changed
            table: node_field_data
            field: changed
            relationship: none
            group_type: group
            admin_label: ''
            entity_type: node
            entity_field: changed
            plugin_id: date
            order: ASC
            expose:
              label: Changed
              field_identifier: changed
            exposed: true
            granularity: second
          title:
            id: title
            table: node_field_data
            field: title
            relationship: none
            group_type: group
            admin_label: ''
            entity_type: node
            entity_field: title
            plugin_id: standard
            order: ASC
            expose:
              label: Title
              field_identifier: title
            exposed: true
      cache_metadata:
        contexts:
          - url.query_args
          - 'url.query_args:sort_by'
          - 'url.query_args:sort_order'
