adding: {  }
removing:
  display:
    block_3:
      display_options:
        header:
          area:
            id: area
            table: views
            field: area
            relationship: none
            group_type: group
            admin_label: ''
            plugin_id: text
            empty: false
            content:
              value: "{% if name %}\r\n<div class=\"magazine-topics__term-name\"><h2 class=\"title\" id=\"page-title\">{{ name }}</h2>\r\n{% endif %}"
              format: stanford_html
            tokenize: true
