adding:
  display:
    default_list_viewfield_block_graphql:
      display_title: 'GraphQL: - Default List View -'
    vertical_teaser_viewfield_block_graphql:
      id: vertical_teaser_viewfield_block_graphql
      display_title: 'GraphQL: Card Grid'
      display_plugin: graphql
      position: 99
      display_options:
        fields:
          su_course_subject:
            id: su_course_subject
            table: node__su_course_subject
            field: su_course_subject
            relationship: none
            group_type: group
            admin_label: ''
            plugin_id: field
            label: ''
            exclude: false
            alter:
              alter_text: false
              text: ''
              make_link: false
              path: ''
              absolute: false
              external: false
              replace_spaces: false
              path_case: none
              trim_whitespace: true
              alt: ''
              rel: ''
              link_class: ''
              prefix: ''
              suffix: ''
              target: ''
              nl2br: false
              max_length: 0
              word_boundary: true
              ellipsis: true
              more_link: false
              more_link_text: ''
              more_link_path: ''
              strip_tags: true
              trim: false
              preserve_tags: ''
              html: false
            element_type: ''
            element_class: ''
            element_label_type: ''
            element_label_class: ''
            element_label_colon: false
            element_wrapper_type: ''
            element_wrapper_class: ''
            element_default_classes: false
            empty: ''
            hide_empty: false
            empty_zero: false
            hide_alter_empty: true
            click_sort_column: target_id
            type: entity_reference_label
            settings:
              link: false
            group_column: target_id
            group_columns: {  }
            group_rows: true
            delta_limit: 0
            delta_offset: 0
            delta_reversed: false
            delta_first_last: false
            multi_type: separator
            separator: ', '
            field_api_classes: false
          su_course_code:
            id: su_course_code
            table: node__su_course_code
            field: su_course_code
            relationship: none
            group_type: group
            admin_label: ''
            plugin_id: field
            label: ''
            exclude: false
            alter:
              alter_text: false
              text: ''
              make_link: false
              path: ''
              absolute: false
              external: false
              replace_spaces: false
              path_case: none
              trim_whitespace: true
              alt: ''
              rel: ''
              link_class: ''
              prefix: ''
              suffix: ''
              target: ''
              nl2br: false
              max_length: 0
              word_boundary: true
              ellipsis: true
              more_link: false
              more_link_text: ''
              more_link_path: ''
              strip_tags: false
              trim: false
              preserve_tags: ''
              html: false
            element_type: ''
            element_class: ''
            element_label_type: ''
            element_label_class: ''
            element_label_colon: false
            element_wrapper_type: ''
            element_wrapper_class: ''
            element_default_classes: false
            empty: ''
            hide_empty: false
            empty_zero: false
            hide_alter_empty: true
            click_sort_column: value
            type: string
            settings:
              link_to_entity: false
            group_column: value
            group_columns: {  }
            group_rows: true
            delta_limit: 0
            delta_offset: 0
            delta_reversed: false
            delta_first_last: false
            multi_type: separator
            separator: ', '
            field_api_classes: false
          su_course_academic_year:
            id: su_course_academic_year
            table: node__su_course_academic_year
            field: su_course_academic_year
            relationship: none
            group_type: group
            admin_label: ''
            plugin_id: field
            label: ''
            exclude: false
            alter:
              alter_text: false
              text: ''
              make_link: false
              path: ''
              absolute: false
              external: false
              replace_spaces: false
              path_case: none
              trim_whitespace: false
              alt: ''
              rel: ''
              link_class: ''
              prefix: ''
              suffix: ''
              target: ''
              nl2br: false
              max_length: 0
              word_boundary: true
              ellipsis: true
              more_link: false
              more_link_text: ''
              more_link_path: ''
              strip_tags: false
              trim: false
              preserve_tags: ''
              html: false
            element_type: ''
            element_class: ''
            element_label_type: ''
            element_label_class: ''
            element_label_colon: false
            element_wrapper_type: ''
            element_wrapper_class: ''
            element_default_classes: true
            empty: ''
            hide_empty: false
            empty_zero: false
            hide_alter_empty: true
            click_sort_column: value
            type: string
            settings:
              link_to_entity: false
            group_column: value
            group_columns: {  }
            group_rows: true
            delta_limit: 0
            delta_offset: 0
            delta_reversed: false
            delta_first_last: false
            multi_type: separator
            separator: ', '
            field_api_classes: false
          title:
            id: title
            table: node_field_data
            field: title
            relationship: none
            group_type: group
            admin_label: ''
            plugin_id: field
            label: ''
            exclude: false
            alter:
              alter_text: false
              text: ''
              make_link: false
              path: ''
              absolute: false
              external: false
              replace_spaces: false
              path_case: none
              trim_whitespace: false
              alt: ''
              rel: ''
              link_class: ''
              prefix: ''
              suffix: ''
              target: ''
              nl2br: false
              max_length: 0
              word_boundary: true
              ellipsis: true
              more_link: false
              more_link_text: ''
              more_link_path: ''
              strip_tags: false
              trim: false
              preserve_tags: ''
              html: false
            element_type: ''
            element_class: ''
            element_label_type: ''
            element_label_class: ''
            element_label_colon: true
            element_wrapper_type: ''
            element_wrapper_class: ''
            element_default_classes: true
            empty: ''
            hide_empty: false
            empty_zero: false
            hide_alter_empty: true
            click_sort_column: value
            type: string
            settings:
              link_to_entity: true
            group_column: value
            group_columns: {  }
            group_rows: true
            delta_limit: 0
            delta_offset: 0
            delta_reversed: false
            delta_first_last: false
            multi_type: separator
            separator: ', '
            field_api_classes: false
          body:
            id: body
            table: node__body
            field: body
            relationship: none
            group_type: group
            admin_label: ''
            plugin_id: field
            label: ''
            exclude: false
            alter:
              alter_text: false
              text: ''
              make_link: false
              path: ''
              absolute: false
              external: false
              replace_spaces: false
              path_case: none
              trim_whitespace: false
              alt: ''
              rel: ''
              link_class: ''
              prefix: ''
              suffix: ''
              target: ''
              nl2br: false
              max_length: 0
              word_boundary: true
              ellipsis: true
              more_link: false
              more_link_text: ''
              more_link_path: ''
              strip_tags: false
              trim: false
              preserve_tags: ''
              html: false
            element_type: ''
            element_class: ''
            element_label_type: ''
            element_label_class: ''
            element_label_colon: false
            element_wrapper_type: ''
            element_wrapper_class: ''
            element_default_classes: true
            empty: ''
            hide_empty: false
            empty_zero: false
            hide_alter_empty: true
            click_sort_column: value
            type: text_default
            settings: {  }
            group_column: value
            group_columns: {  }
            group_rows: true
            delta_limit: 0
            delta_offset: 0
            delta_reversed: false
            delta_first_last: false
            multi_type: separator
            separator: ', '
            field_api_classes: false
          su_course_instructors:
            id: su_course_instructors
            table: node__su_course_instructors
            field: su_course_instructors
            relationship: none
            group_type: group
            admin_label: ''
            plugin_id: field
            label: ''
            exclude: false
            alter:
              alter_text: false
              text: ''
              make_link: false
              path: ''
              absolute: false
              external: false
              replace_spaces: false
              path_case: none
              trim_whitespace: false
              alt: ''
              rel: ''
              link_class: ''
              prefix: ''
              suffix: ''
              target: ''
              nl2br: false
              max_length: 0
              word_boundary: true
              ellipsis: true
              more_link: false
              more_link_text: ''
              more_link_path: ''
              strip_tags: false
              trim: false
              preserve_tags: ''
              html: false
            element_type: ''
            element_class: ''
            element_label_type: ''
            element_label_class: ''
            element_label_colon: false
            element_wrapper_type: ''
            element_wrapper_class: ''
            element_default_classes: true
            empty: ''
            hide_empty: false
            empty_zero: false
            hide_alter_empty: true
            click_sort_column: value
            type: string
            settings:
              link_to_entity: false
            group_column: value
            group_columns: {  }
            group_rows: true
            delta_limit: 0
            delta_offset: 0
            delta_reversed: false
            delta_first_last: false
            multi_type: separator
            separator: ', '
            field_api_classes: false
          view_node:
            id: view_node
            table: node
            field: view_node
            relationship: none
            group_type: group
            admin_label: ''
            entity_type: node
            plugin_id: entity_link
            label: ''
            exclude: false
            alter:
              alter_text: false
              text: ''
              make_link: false
              path: ''
              absolute: false
              external: false
              replace_spaces: false
              path_case: none
              trim_whitespace: false
              alt: ''
              rel: ''
              link_class: ''
              prefix: ''
              suffix: ''
              target: ''
              nl2br: false
              max_length: 0
              word_boundary: true
              ellipsis: true
              more_link: false
              more_link_text: ''
              more_link_path: ''
              strip_tags: false
              trim: false
              preserve_tags: ''
              html: false
            element_type: ''
            element_class: ''
            element_label_type: ''
            element_label_class: ''
            element_label_colon: false
            element_wrapper_type: ''
            element_wrapper_class: ''
            element_default_classes: true
            empty: ''
            hide_empty: false
            empty_zero: false
            hide_alter_empty: true
            text: view
            output_url_as_text: true
            absolute: false
          su_course_id:
            id: su_course_id
            table: node__su_course_id
            field: su_course_id
            relationship: none
            group_type: group
            admin_label: ''
            plugin_id: field
            label: ''
            exclude: false
            alter:
              alter_text: false
              text: ''
              make_link: false
              path: ''
              absolute: false
              external: false
              replace_spaces: false
              path_case: none
              trim_whitespace: false
              alt: ''
              rel: ''
              link_class: ''
              prefix: ''
              suffix: ''
              target: ''
              nl2br: false
              max_length: 0
              word_boundary: true
              ellipsis: true
              more_link: false
              more_link_text: ''
              more_link_path: ''
              strip_tags: false
              trim: false
              preserve_tags: ''
              html: false
            element_type: ''
            element_class: ''
            element_label_type: ''
            element_label_class: ''
            element_label_colon: false
            element_wrapper_type: ''
            element_wrapper_class: ''
            element_default_classes: true
            empty: ''
            hide_empty: false
            empty_zero: false
            hide_alter_empty: true
            click_sort_column: value
            type: number_integer
            settings:
              thousand_separator: ''
              prefix_suffix: true
            group_column: value
            group_columns: {  }
            group_rows: true
            delta_limit: 0
            delta_offset: 0
            delta_reversed: false
            delta_first_last: false
            multi_type: separator
            separator: ', '
            field_api_classes: false
        pager:
          type: full
          options:
            offset: 0
            pagination_heading_level: h4
            items_per_page: 3
            total_pages: null
            id: 0
            tags:
              next: 'Next ›'
              previous: '‹ Previous'
              first: '« First'
              last: 'Last »'
            expose:
              items_per_page: true
              items_per_page_label: items
              items_per_page_options: '3,6,9,12,15,18,21,24,27,30,33,36,39,42,45,48,51,54,57,60,63,66,69,72,75,78,81,84,87,90,93,96,99'
              items_per_page_options_all: true
              items_per_page_options_all_label: all
              offset: true
              offset_label: offset
            quantity: 9
        style:
          type: graphql
          options: null
        row:
          type: graphql_entity
          options: null
        defaults:
          pager: false
          style: false
          row: false
          fields: false
        display_description: 'The card grid list view field block'
        display_extenders: {  }
        graphql_query_name: stanfordCoursesCardGrid
      cache_metadata:
        max-age: -1
        contexts:
          - 'languages:language_content'
          - 'languages:language_interface'
          - url
          - url.query_args
          - 'user.node_grants:view'
          - user.permissions
        tags:
          - 'config:field.storage.node.body'
          - 'config:field.storage.node.su_course_academic_year'
          - 'config:field.storage.node.su_course_code'
          - 'config:field.storage.node.su_course_id'
          - 'config:field.storage.node.su_course_instructors'
          - 'config:field.storage.node.su_course_subject'
removing:
  display:
    default_list_viewfield_block_graphql:
      display_title: 'GraphQL: List'
      display_options:
        exposed_form:
          type: graphql
          options:
            submit_button: Apply
            reset_button: 0
            reset_button_label: Reset
            exposed_sorts_label: 'Sort by'
            expose_sort_order: 1
            sort_asc_label: Asc
            sort_desc_label: Desc
        sorts:
          title:
            id: title
            table: node_field_data
            field: title
            relationship: none
            group_type: group
            admin_label: ''
            entity_type: node
            entity_field: title
            plugin_id: standard
            order: ASC
            expose:
              label: Title
              field_identifier: title
            exposed: true
          created:
            id: created
            table: node_field_data
            field: created
            relationship: none
            group_type: group
            admin_label: ''
            entity_type: node
            entity_field: created
            plugin_id: date
            order: ASC
            expose:
              label: 'Authored on'
              field_identifier: created
            exposed: true
            granularity: second
          changed:
            id: changed
            table: node_field_data
            field: changed
            relationship: none
            group_type: group
            admin_label: ''
            entity_type: node
            entity_field: changed
            plugin_id: date
            order: ASC
            expose:
              label: Changed
              field_identifier: changed
            exposed: true
            granularity: second
        defaults:
          sorts: false
      cache_metadata:
        contexts:
          - 'url.query_args:sort_by'
          - 'url.query_args:sort_order'
