adding:
  field_settings:
    rendered_item:
      configuration:
        view_mode:
          'entity:node':
            stanford_course: search_indexing
            stanford_event: search_indexing
            stanford_event_series: search_indexing
            stanford_opportunity: search_indexing
            stanford_page: search_indexing
            stanford_person: search_indexing
            stanford_policy: search_indexing
            stanford_publication: search_indexing
removing:
  field_settings:
    rendered_item:
      configuration:
        view_mode:
          'entity:node':
            ':default': search_indexing
            stanford_course: ':default'
            stanford_event: ':default'
            stanford_event_series: ':default'
            stanford_media: ':default'
            stanford_opportunity: ':default'
            stanford_page: ':default'
            stanford_person: ':default'
            stanford_policy: ':default'
            stanford_publication: ':default'
  options:
    delete_on_fail: true
