adding:
  dependencies:
    config:
      - views.view.stanford_news
  third_party_settings:
    layout_builder:
      sections:
        -
          components:
            2a5a6a90-b253-44a7-8111-8012baa026ea:
              uuid: 2a5a6a90-b253-44a7-8111-8012baa026ea
              region: main
              configuration:
                id: 'views_block:stanford_news-term_block'
                label: ''
                label_display: '0'
                provider: views
                views_label: ''
                items_per_page: none
              weight: 3
        -
          components:
            2a5a6a90-b253-44a7-8111-8012baa026ea:
              uuid: 2a5a6a90-b253-44a7-8111-8012baa026ea
              region: main
              configuration:
                id: 'views_block:stanford_news-term_block'
                label: ''
                label_display: '0'
                provider: views
                views_label: ''
                items_per_page: none
              weight: 3
removing: {  }
