adding:
  dependencies:
    config:
      - field.field.node.stanford_page.su_department
  content:
    su_department:
      type: options_buttons
      weight: 11
      region: content
      settings: {  }
      third_party_settings: {  }
    syndication:
      type: boolean_checkbox
      weight: 27
      region: content
      settings:
        display_label: true
      third_party_settings: {  }
removing: {  }
