adding:
  permissions:
    - 'view own su_site_algolia'
    - 'view own su_site_algolia_id'
    - 'view own su_site_algolia_index'
    - 'view own su_site_algolia_search'
    - 'view su_site_algolia'
    - 'view su_site_algolia_id'
    - 'view su_site_algolia_index'
    - 'view su_site_algolia_search'
removing:
  dependencies:
    module:
      - graphql
      - printable
  permissions:
    - 'execute graphql_compose_server arbitrary graphql requests'
    - 'execute graphql_compose_server persisted graphql requests'
    - 'view policy_settings config page entity'
    - 'view printer friendly versions'
    - 'view stanford_basic_site_settings config page entity'
    - 'view stanford_global_message config page entity'
    - 'view stanford_local_footer config page entity'
    - 'view stanford_super_footer config page entity'
    - 'view su_event_ext_image'
