adding:
  printable_entities_bundles:
    node:
      stanford_news: true
      spotlight: true
      stanford_opportunity: false
    taxonomy_term:
      affiliation: false
      article_collection: false
      department: false
      event_filters: false
      magazine_issues: false
      magazine_topics: false
      opportunity_sponsor: false
      opportunity_tag_filters: false
      opportunity_type: false
      opportunity_units: false
      person_filters: false
      publication_filters: false
    paragraph:
      stanford_cta_list: false
      stanford_faq: false
      stanford_filtered_lists: false
      stanford_image_cta: false
      stanford_page_title_banner: false
      stanford_stat_card: false
      stanford_stories: false
  css_include: profiles/custom/themes/engineering/dist/css/print.styles.css
removing:
  printable_entities_bundles:
    node:
      stanford_news: false
    paragraph_row:
      node_stanford_page_row: false
      su_pub_rows: false
  css_include: profiles/custom/stanford_profile/themes/stanford_basic/dist/css/print.css
