<?php

/**
 * @file
 * Contains soe_print_sheets.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function soe_print_sheets_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the soe_print_sheets module.
    case 'help.page.soe_print_sheets':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Merges Printable modules functionality with SOE UI/UX.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function soe_print_sheets_theme() {
  return [
    'soe_print_sheets' => [
      'render element' => 'children',
    ],
  ];
}
